name: "cfn-lint-action"
description: "Setup Amazon Cloud Formation Linter (cfn-lint)"
branding:
  icon: "terminal"
  color: "orange"
inputs:
  version:
    description: "The version of the AWS CloudFormation Linter you would like to install"
    required: false
  python:
    description: "The Python interpreter to use for AWS CFN LINT"
    required: false
  command:
    description: "The command you would like AWS CloudFormation Linter to Run"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
