name: 'cfn-lint-action'
author: 'Scott Brenner <scott@scottbrenner.me>'
description: 'GitHub Action for CloudFormation Linter'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'box'
  color: 'yellow'
